### ISSUE TITLE
Prepare PR to merge into Verificarlo

### ISSUE THREAD

**Issue by pablooliveira** [DMAK-CHPS/verificarlo#3]
I think your backend is mature enough to be merged into Verificarlo. Did you have time to implement the changes we discussed during our last meeting ? Do you need help doing the PR against [verificarlo](http://github.com/verificarlo/verificarlo) ?

**Comment by KillianBabilotte** [comment]
The [PR](https://github.com/verificarlo/verificarlo/pull/153) just has been done, I tried to submit our commits as one but I didn't succeed to. So maybe we have to rebase some at your appreciation. I will close this Issue once the PR will be merge.

**Comment by pablooliveira** [comment]
Can you please add me as developer to DMAK-CHPS. I would like to contribute some fixes on DMAK-CHPS dev branch ?

**Comment by KillianBabilotte** [comment]
Of course, I have sent you an invitation !
